import 'package:get/get.dart';

class Translate extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'home': 'Home',
          'players': 'Players',
          'tables': 'Tables',
          'tablename': 'Table Name',
          'tablespage': 'Tables Page',
          'tablepriceperhour': "Table Price Per Hour",
          'payment': 'Payment',
          'playername': 'Player Name',
          'playerphonenumber': 'Player Phone',
          'addplayer': 'Add Player',
          'editplayer': 'Edit Player',
          'playeredited': 'Player Successfully Edited',
          'group': 'Group',
          'addplayerspage': 'Add Players Page',
          'addtable': 'Add Table',
          'edittable': 'Edit Table',
          'startgame': 'Start Game',
          'endgame': 'End Game',
          'openclose': 'Open Close Table',
          'playerone': 'Player One',
          'playertwo': 'Player Two',
          'starttime': 'Start Time',
          'delete': 'Delete',
          'edit': 'Edit',
          'paid': 'Paid',
          'payments': 'Payments',
          'clearpaymentshistory': 'Clear Payments History',
          'paymenthistory': 'Payment History',
          'submit': 'Submit',
          'enterplayername': 'Enter Player Name',
          'wholostgame': 'Who Lost Game!?',
          'paymentsbills': 'Payments Bills',
          'clubname': 'Snooker Club',
          'playereditpage': 'Player Edit Page',
          'playeraddpage': 'Player Add Page',
          'playeraddedtolist': 'Player Added To List',
          'nightmode': 'Night Mode',
          'tableadedsuccfullyess': ' Aded Successfully To Tables List',
          'tableeditedsuccfullyess': 'Table Edited Successfully ',
          'endgametablemassage': 'Added To Payments List',
          'tableactive': 'َActive',
          'loser': 'Loser',
          'date': 'Date',
          'price': 'Price',
          'presstwicetoexit': 'Press Back Again To Exit',
          'connecttionlost': 'Please Check Your Network Connection !!',
          'newslistupdate': 'News List Updated !!',
          'news': 'News',
          'connectionlost': 'Connection Lost',
          'openinchrome': 'Open In Google Chrome'
        },
        'fa': {
          'home': 'خانه',
          'players': 'بازیکن ها',
          'tables': 'میزها',
          'tablename': 'نام میز',
          'tablepriceperhour': 'قیمت میز بر ساعت',
          'tablespage': 'صفحه میزها',
          'payment': 'صورتحصاب',
          'playername': ' نام بازیکن',
          'playerphonenumber': ' تلفن بازیکن',
          'addplayer': 'افزودن بازیکن',
          'editplayer': 'ویرایش بازیکن',
          'playeredited': 'بازیکن با موفقیت ویرایش شد',
          'group': 'گروه',
          'addplayerspage': 'صفحه افزودن بازیکن',
          'addtable': 'افزودن میز',
          'edittable': 'ویرایش میز',
          'startgame': 'شروع بازی',
          'endgame': 'پایان بازی',
          'openclose': 'باز و بست میز',
          'playerone': 'بازیکن یک',
          'playertwo': 'بازیکن دو',
          'starttime': 'زمان شروع',
          'delete': 'حذف',
          'edit': 'ویرایش',
          'paid': 'پرداخت شد',
          'payments': 'پرداختی ها',
          'clearpaymentshistory': 'پاک کردن تاریخچه',
          'paymenthistory': ' تاریخچه پرداختی ها',
          'submit': 'ثبت',
          'enterplayername': 'نام بازیکن را وارد کنید',
          'wholostgame': 'کی بازی رو باخت؟',
          'paymentsbills': 'صورت حساب صندوق',
          'clubname': 'باشگاه بیلیارد',
          'playereditpage': 'صفحه ویرایش بازیکن',
          'playeraddpage': 'صفحه افزودن بازیکن',
          'playeraddedtolist': 'بازیکن به لیست اضافه شد',
          'nightmode': 'حالت شب',
          'tableadedsuccfullyess': ' به لیست میزها اضافه شد',
          'tableeditedsuccfullyess': ' با موفقیت ویرایش شد ',
          'endgametablemassage': 'به لیست پرداختی اضافه شد',
          'tableactive': 'فعال',
          'loser': 'بازنده',
          'date': 'تاریخ',
          'price': 'قیمت',
          'presstwicetoexit': 'برای خروج دوباره برگشت را بزنید',
          'connecttionlost': 'خطای اتصال به شبکه ',
          'newslistupdate': 'لیست اخبار بروز شد !!',
          'news': 'اخبار',
          'connectionlost': 'خطا در شبکه !!',
          'openinchrome': 'رفتن به صفحه خبر با گوکل کروم',
        }
      };
}
