import 'package:get/get.dart';

class Translate extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'home': 'Home',
          'players': 'Players',
          'tables': 'Tables',
          'tablename': 'Table',
          'tablespage': 'Tables Page',
          'tablepriceperhour': "Table Price Per Hour",
          'payment': 'Payment',
          'playername': 'Name',
          'playerphonenumber': 'Phone',
          'addplayer': 'Add Player',
          'editplayer': 'Edit Player',
          'playeredited': 'Player Successfully Edited',
          'group': 'Group',
          'addtable': 'Add Table',
          'edittable': 'Edit Table',
          'startgame': 'Start Game',
          'endgame': 'End Game',
          'openclose': 'Open Close Table',
          'playerone': 'Player One',
          'playertwo': 'Player Two',
          'starttime': 'Start Time',
          'delete': 'Delete',
          'edit': 'Edit',
          'paid': 'Paid',
          'payments': 'Payments',
          'clearpaymentshistory': 'Clear Payments History',
          'paymenthistory': 'Payment History',
          'submit': 'Submit',
          'enterplayername': 'Enter Player Name',
          'wholostgame': 'Who Lost Game!?',
          'paymentsbills': 'Payments Bills',
          'clubname': 'Snooker Club',
          'playereditpage': 'Player Edit Page',
          'playeraddpage': 'Player Add Page',
          'playeraddedtolist': ' Added To Players List',
          'nightmode': 'Night Mode',
          'tableadedsuccfullyess': ' Aded Successfully To Tables List',
          'tableeditedsuccfullyess': 'Table Edited Successfully ',
          'endgametablemassage': 'Added To Payments List',
          'tableactive': 'َActive',
          'loser': 'Loser',
          'date': 'Date',
          'price': 'Price',
          'hour': 'Hour(s)',
          'minute': 'Minute(s)',
          'presstwicetoexit': 'Press Back Again To Exit',
          'connecttionlost': 'Please Check Your Network Connection !!',
          'newslistupdate': 'News List Updated !!',
          'news': 'News',
          'connectionlost': 'Connection Lost',
          'openinchrome': 'Open In Google Chrome',
          'cantbenull': 'Cant Be Empty',
          'areyousuretodelete':
              'Are You Sure About to Remove All Payments List !!? This Action Cant be Undo !!!!',
          'selectone': 'Please Select Loser',
          'moneycurrency': 'Dollar(s)',
          'warning': 'warning',
          'areyousuredelete': 'Are You Sure To Delete This Table ??',
          'privacy': 'Privacy Policy',
          'privacytext':
              'Dear user! The information received from your customers is for your use in the program and will not be used in any way on any social networks or the internet.',
          'undrestand': 'Undrestand',
        },
        'fa': {
          'home': 'خانه',
          'players': 'بازیکن ها',
          'tables': 'میزها',
          'tablename': 'نام میز',
          'tablepriceperhour': 'قیمت میز بر ساعت',
          'payment': 'صورتحصاب',
          'playername': 'نام ',
          'playerphonenumber': ' شماره تلفن',
          'addplayer': 'افزودن بازیکن',
          'editplayer': 'ویرایش بازیکن',
          'playeredited': 'بازیکن با موفقیت ویرایش شد',
          'group': 'گروه',
          'addtable': 'افزودن میز',
          'edittable': 'ویرایش میز',
          'startgame': 'شروع بازی',
          'endgame': 'پایان بازی',
          'openclose': 'باز و بست میز',
          'playerone': 'بازیکن یک',
          'playertwo': 'بازیکن دو',
          'starttime': 'زمان شروع',
          'delete': 'حذف',
          'edit': 'ویرایش',
          'paid': 'پرداخت شد',
          'payments': 'پرداختی ها',
          'clearpaymentshistory': 'پاک کردن تاریخچه',
          'paymenthistory': ' تاریخچه پرداختی ها',
          'submit': 'ثبت',
          'enterplayername': 'نام بازیکن را وارد کنید',
          'wholostgame': 'کی بازی رو باخت؟',
          'paymentsbills': 'صورت حساب صندوق',
          'clubname': 'باشگاه بیلیارد',
          'playereditpage': 'صفحه ویرایش بازیکن',
          'playeraddpage': 'صفحه افزودن بازیکن',
          'playeraddedtolist': ' به لیست بازیکن ها اضافه شد',
          'nightmode': 'حالت شب',
          'tableadedsuccfullyess': ' به لیست میزها اضافه شد',
          'tableeditedsuccfullyess': ' با موفقیت ویرایش شد ',
          'endgametablemassage': 'به لیست صورتحساب ها اضافه شد',
          'tableactive': 'فعال',
          'loser': 'بازنده',
          'date': 'تاریخ',
          'price': 'قیمت',
          'hour': 'ساعت',
          'minute': 'دقیقه',
          'presstwicetoexit': 'برای خروج دوباره برگشت را بزنید',
          'connecttionlost': 'خطای اتصال به شبکه ',
          'newslistupdate': 'لیست اخبار بروز شد !!',
          'news': 'اخبار',
          'connectionlost': 'خطا در شبکه !!',
          'openinchrome': 'رفتن به صفحه خبر با گوکل کروم',
          'cantbenull': 'نمیتواند خالی باشد',
          'areyousuretodelete':
              'آیا از حذف لیست تمامی پرداختی ها مطمِن هستید !!؟؟ پس از حذف اطلاعات قابل بازگشت نیستند !!',
          'selectone': 'لطفا بازنده را مشخص کنید',
          'moneycurrency': 'تومان',
          'warning': 'هشدار',
          'areyousuredelete': 'از حذف این میز مطمئن هستید؟؟',
          'privacy': 'حریم خصوصی',
          'privacytext':
              'کاربر گرامی!!! اطاعات دریافتی مشتریان شما جهت استفاده شما در برنامه می باشد، در هیچکدام یک از شبکه های اجتماعی و اینترنت هیچگونه استفاده ای نخواهد شد.    ',
          'undrestand': 'فهمیدم',
        }
      };
}
